### ISSUE TITLE
"mas sobre mi"

### ISSUE THREAD

**Issue by h4ckxel** [SkipperPA/Skipper.25#5]
falta poner en el readme mas datos, dime que le puedo agregar

**Comment by SkipperPA** [comment]
Man, soy estudiante de ciberseguridad, jugador de CTF, agrégale algo que mencione  chagpt, no tengo un recorrido grande en el mundo aún. Este será un repositorio con mis apuntes y aportes, que podrán ayudar a los que están iniciando como yo, en este mundo.

**Comment by SkipperPA** [comment]
Nombres, ya vi que colocaste algo bueno, te iba a comentar que no coloques mi foto real, sino alguno de un pinguino de hacking o de las que te pasé al instagram.

**Comment by h4ckxel** [comment]
vale, como tomo en cuenta
